export const LOWEST_NODE_VERSION = '18.12.1'
export const DEFAULT_CLI_PACKAGE_HOME_PATH = '.eo-cli'
export const DEFAULT_CLI_PACKAGE_DEPENDENCIES_DIR_NAME = 'dependencies'
export const NPM_URL = 'https://registry.npmjs.org'
export const NPM_MIRROR_URL = 'https://registry.npmmirror.com'
